apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pulsar.fullname" . }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pulsar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/pulsar_conf: {{ include (print $.Template.BasePath "/configs-pulsar.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "pulsar.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pulsar.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PULSAR_CONFIG_PRIVATE_TOKEN
            value: {{ .Values.api_key }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range $key,$entry := .Values.configs }}
            {{ if $entry -}}
            - name: pulsar-conf-files
              mountPath: /pulsar/{{ $key }}
              subPath: {{ $key }}
            {{- end -}}
            {{- end }}
            - name: pulsar-data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- if .Values.refdata.enabled }}
            - name: pulsar-refdata
              mountPath: /cvmfs/data.galaxyproject.org
            {{- if eq .Values.refdata.type "cvmfs" }}
              subPath: data.galaxyproject.org
              # CVMFS automount volumes must be mounted with HostToContainer mount propagation.
              mountPropagation: HostToContainer
            {{- end }}
            {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: pulsar-conf-files
          {{- if .Values.useSecretConfigs }}
          secret:
            secretName: {{ template "pulsar.fullname" . }}-configs
          {{- else }}
          configMap:
            name: {{ template "pulsar.fullname" . }}-configs
          {{- end }}
        - name: pulsar-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "pulsar.pvcname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if $.Values.refdata.enabled }}
        - name: pulsar-refdata
          persistentVolumeClaim:
            claimName: {{ template "pulsar.fullname" $ -}}-refdata-pvc
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
