{{- if .Values.refdata.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pulsar.fullname" $ }}-refdata-pvc
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.refdata.pvc.size }}
{{- if eq $.Values.refdata.type "cvmfs" }}
  storageClassName: {{ tpl .Values.cvmfs.storageClassName . }}
{{- end }}
{{- end }}
